name: Build and Release v2dat

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: arm64
            goos: linux
          - goarch: arm
            goos: linux
            goarm: 7
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} go build -v -ldflags="-s -w" -o v2dat .
          # Формируем имя: v2dat-linux-arm-v7.tar.gz или v2dat-linux-amd64.tar.gz
          SUFFIX="${{ matrix.goarm && format('-v{0}', matrix.goarm) || '' }}"
          tar -czf v2dat-${{ matrix.goos }}-${{ matrix.goarch }}${SUFFIX}.tar.gz v2dat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: "*.tar.gz"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
